FROM maven:3.9-eclipse-temurin-21-alpine AS build
WORKDIR /app

COPY pom.xml .
COPY EmployeeManager/pom.xml ./EmployeeManager/
COPY EmployeeManager/src ./EmployeeManager/src

RUN mvn clean package -DskipTests -pl EmployeeManager -am

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/EmployeeManager/target/EmployeeManager-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 9090
ENTRYPOINT ["java", "-jar", "app.jar"]